openapi: 3.0.3
info:
  title: Arlo REST Public API
  description: API for accessing Arlo public resources from a specific platform
  version: '2012-02-01'
servers:
  - url: https://{platform_name}.arlo.co/api/2012-02-01/pub/resources
    variables:
      platform_name:
        default: demo
        description: The subdomain of the Arlo platform.
paths:
  /onlineactivitysearch:
    get:
      summary: Search for online activities
      description: Retrieves a list of online activities (e-learning or self-paced learning) with associated delivery information, registration URLs, offers, and tags.
      parameters:
        - name: filter
          in: query
          required: false
          description: Filter expression to apply to the search results.
          schema:
            type: string
        - name: skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
        - name: top
          in: query
          required: false
          description: Number of records to return for pagination.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of online activities.
          content:
            application/json:
              schema:
                description: schema
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Resource not found.
  /eventsearch:
    get:
      summary: Search for online events
      description: Retrieves a list of events with associated delivery information, registration URLs, offers, and tags.
      parameters:
        - name: filter
          in: query
          required: false
          description: Filter expression to apply to the search results.
          schema:
            type: string
        - name: skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
        - name: top
          in: query
          required: false
          description: Number of records to return for pagination.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of events.
          content:
            application/json:
              schema:
                description: schema
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Resource not found.
  /eventtemplatesearch:
    get:
      summary: Search for online event Templates
      description: Retrieves a list of event templates
      parameters:
        - name: filter
          in: query
          required: false
          description: Filter expression to apply to the search results.
          schema:
            type: string
        - name: skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
        - name: top
          in: query
          required: false
          description: Number of records to return for pagination.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of event templates.
          content:
            application/json:
              schema:
                description: schema
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Resource not found.
  /eventtemplates:
    get:
      summary: Retrieve a collection of event templates
      description: Fetches a list of event templates, each representing the shared basic content details of an event.
      parameters:
        - name: filter
          in: query
          required: false
          description: Filter expression to apply to the collection.
          schema:
            type: string
        - name: skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
        - name: top
          in: query
          required: false
          description: Number of records to return for pagination.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the event templates collection.
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Event templates not found.
  /eventtemplates/{TemplateID}:
    get:
      summary: Retrieve a specific event template
      description: Fetches details of a specific event template by its unique identifier.
      parameters:
        - name: TemplateID
          in: path
          required: true
          description: Unique identifier for the event template.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the event template.
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Event template not found.
  /eventtemplatecategories:
    get:
      summary: Retrieve a collection of event template categories
      description: Fetches a list of event template categories, each representing the shared basic content details of an event.
      parameters:
        - name: filter
          in: query
          required: false
          description: Filter expression to apply to the collection.
          schema:
            type: string
        - name: skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
        - name: top
          in: query
          required: false
          description: Number of records to return for pagination.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the event template categories collection.
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Event templates not found.
  /eventtemplatecategories/{EventTemplateCategoryID}:
    get:
      summary: Retrieve a specific event template
      description: Fetches details of a specific event template category by its unique identifier.
      parameters:
        - name: EventTemplateCategoryID
          in: path
          required: true
          description: Unique identifier for the event template category.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the event template.
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Event template not found.
  /eventtemplatecategoryitems:
    get:
      summary: Retrieve a collection of event template category items
      description: Fetches a list of event template category items, each representing the shared basic content details of an event category items.
      parameters:
        - name: filter
          in: query
          required: false
          description: Filter expression to apply to the collection.
          schema:
            type: string
        - name: skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
        - name: top
          in: query
          required: false
          description: Number of records to return for pagination.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the event template category items collection.
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Event templates not found.
  /eventtemplatecategoryitems/{EventTemplateCategoryItemID}:
    get:
      summary: Retrieve a specific event template category Item
      description: Fetches details of a specific event template category item by its unique identifier.
      parameters:
        - name: EventTemplateCategoryItemID
          in: path
          required: true
          description: Unique identifier for the event template category item.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the event template category item.
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Event template not found.
  /events/{EventID}/registrations:
    post:
      summary: Submit a registration for an event
      description: Allows submission of registration information for a specific event. This is a write-only resource; retrieval of registration information is not supported.
      parameters:
        - name: EventID
          in: path
          required: true
          description: Unique identifier for the event.
          schema:
            type: integer
        - name: region
          in: query
          required: false
          description: The region in which the registration is being submitted (e.g., `nz` for New Zealand).
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: schema xml
              type: object
      responses:
        '201':
          description: Registration successfully submitted.
        '400':
          description: Bad request due to invalid parameters.
        '409':
          description: Conflict due to duplicate registration or event being full.
        '404':
          description: Event not found or registration period closed.
  /presenters:
    get:
      summary: Retrieve a collection of presenters
      description: Fetches a list of presenters
      parameters:
        - name: filter
          in: query
          required: false
          description: Filter expression to apply to the collection.
          schema:
            type: string
        - name: skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
        - name: top
          in: query
          required: false
          description: Number of records to return for pagination.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the presenters collection.
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Presenters not found.
  /presenters/{PresenterID}:
    get:
      summary: Retrieve a specific presenter
      description: Fetches details of a specific presenter by its unique identifier.
      parameters:
        - name: PresenterID
          in: path
          required: true
          description: Unique identifier for the presenter
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the presenter
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Event template not found.
  /venues:
    get:
      summary: Retrieve a collection of venues
      description: Fetches a list of venues
      parameters:
        - name: filter
          in: query
          required: false
          description: Filter expression to apply to the collection.
          schema:
            type: string
        - name: skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
        - name: top
          in: query
          required: false
          description: Number of records to return for pagination.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the venues collection.
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: venues not found.
  /venues/{VenueID}:
    get:
      summary: Retrieve a specific venue
      description: Fetches details of a specific venue by its unique identifier.
      parameters:
        - name: VenueID
          in: path
          required: true
          description: Unique identifier for the venue
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the venue
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Event template not found.
  /advertisedoffers:
    get:
      summary: Retrieve a collection of Advertised offers
      description: Fetches a list of Advertised offers
      parameters:
        - name: filter
          in: query
          required: false
          description: Filter expression to apply to the collection.
          schema:
            type: string
        - name: skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
        - name: top
          in: query
          required: false
          description: Number of records to return for pagination.
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of the Advertised offers collection.
          content:
            application/json:
              schema:
                description: schema 
                type: object
        '400':
          description: Bad request due to invalid parameters.
        '404':
          description: Advertised offers not found.
